import { PageHeader, EmptyState } from "@/components/ui";
import { ApiForm } from "@/components/management-form";
import { ManagementDemo, ManagementForbidden, managementDate, roleLabels } from "@/components/management-state";
import { readWorkspace } from "@/lib/workspace";
import { listInvitations, listMembers } from "@/modules/organizations/service";
import { listProjects } from "@/modules/projects/persistent";

export const metadata = { title: "Equipo y accesos" };
export default async function TeamPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const workspace = await readWorkspace(typeof params.org === "string" ? params.org : undefined);
  const { organization, identity, canManage } = workspace;
  if (workspace.isDemo || !identity) return <><PageHeader title="Equipo y accesos" description="Invitaciones, membresías y permisos por proyecto." /><ManagementDemo area="La gestión del equipo" organizationId={organization.id} /></>;
  if (!canManage) return <><PageHeader title="Equipo y accesos" /><ManagementForbidden /></>;
  const projectSearch = typeof params.projectSearch === "string" ? params.projectSearch.slice(0, 100) : "";
  const [members, invitations, projects] = await Promise.all([listMembers(identity, organization.id), listInvitations(identity, organization.id), listProjects(identity, organization.id, { pageSize: 100, search: projectSearch })]);
  const endpoint = `/api/v1/organizations/${organization.id}`;
  const roleOptions = Object.entries(roleLabels).filter(([role]) => role !== "owner" || organization.role === "owner").map(([value, label]) => ({ value, label }));
  return <>
    <PageHeader title="Equipo y accesos" description="Invita personas a la empresa y asigna a técnicos y propietarios únicamente sus instalaciones." />
    <p className="notice">El titular y los administradores consultan toda la empresa. Los técnicos y propietarios consultan solo los proyectos asignados.</p>
    <form className="toolbar selection-search" method="get"><input type="hidden" name="org" value={organization.id} /><label className="field">Buscar proyectos para invitar<input type="search" name="projectSearch" defaultValue={projectSearch} maxLength={100} /></label><button className="button button-secondary" type="submit">Buscar proyectos</button><span className="muted">{projects.total} coincidencias · Hasta 100 opciones</span></form>
    <section className="panel"><div className="panel-header"><h2 className="section-title">Invitar a una persona</h2></div><ApiForm endpoint={`${endpoint}/invitations`} submitLabel="Crear enlace de invitación" fields={[{ name: "email", label: "Correo electrónico", type: "email", required: true }, { name: "role", label: "Rol en la empresa", type: "select", defaultValue: "technician", required: true, options: roleOptions }, { name: "projectIds", label: "Proyectos para técnico o propietario", type: "multiselect", options: projects.items.map((project) => ({ value: project.id, label: project.name })), hint: "Deja vacío para titulares y administradores. El enlace vence en siete días y se muestra una sola vez para compartirlo manualmente." }]} /></section>
    <section className="panel"><div className="panel-header"><h2 className="section-title">Miembros de la empresa</h2><span className="muted">{members.length} personas</span></div><div className="table-container"><p className="table-scroll-hint">Desliza la tabla para consultar todos los datos y acciones.</p><div className="table-wrap" tabIndex={0} role="region" aria-label="Miembros de la empresa, desplazable"><table className="data-table management-table"><caption className="visually-hidden">Miembros, roles y estado de acceso</caption><thead><tr><th scope="col">Persona</th><th scope="col">Rol</th><th scope="col">Acceso</th><th scope="col">Gestión</th></tr></thead><tbody>{members.map((member) => <tr key={member.id}><th scope="row">{member.user.name ?? member.user.email}<span className="table-subtitle muted">{member.user.email}</span></th><td>{roleLabels[member.role]}</td><td>{member.status === "active" ? "Activo" : member.status === "disabled" ? "Deshabilitado" : "Invitado"}<span className="table-subtitle muted">{member.role === "owner" || member.role === "administrator" ? "Todos los proyectos" : `${member.siteAccess.length} proyectos asignados`}</span></td><td>{member.role === "owner" && organization.role !== "owner" ? <span className="muted">Gestionado por un titular</span> : <details><summary>Editar acceso</summary><ApiForm endpoint={`${endpoint}/memberships/${member.id}`} method="PATCH" submitLabel="Guardar acceso" fields={[{ name: "role", label: "Rol", type: "select", defaultValue: member.role, required: true, options: roleOptions }, { name: "status", label: "Estado", type: "select", required: true, defaultValue: member.status === "active" ? "active" : "disabled", options: [{ value: "active", label: "Activo" }, { value: "disabled", label: "Deshabilitado" }], hint: "Cambiar el rol o deshabilitar retira las asignaciones de proyectos. Debe permanecer un titular activo." }]} /></details>}</td></tr>)}</tbody></table></div></div></section>
    <section className="panel"><div className="panel-header"><h2 className="section-title">Últimas invitaciones</h2><span className="muted">Hasta 100 invitaciones</span></div>{invitations.length === 0 ? <EmptyState title="Aún no hay invitaciones" description="Crea un enlace para incorporar al primer técnico o propietario." /> : <div className="table-container"><p className="table-scroll-hint">Desliza la tabla para consultar todos los datos y acciones.</p><div className="table-wrap" tabIndex={0} role="region" aria-label="Invitaciones recientes, desplazable"><table className="data-table management-table"><caption className="visually-hidden">Invitaciones sin exponer sus tokens</caption><thead><tr><th scope="col">Destinatario</th><th scope="col">Rol</th><th scope="col">Estado</th><th scope="col">Vencimiento</th><th scope="col">Gestión</th></tr></thead><tbody>{invitations.map((invitation) => <tr key={invitation.id}><th scope="row">{invitation.email}</th><td>{roleLabels[invitation.role]}</td><td>{{ pending: "Pendiente", revoked: "Revocada", accepted: "Aceptada", expired: "Vencida" }[invitation.status]}</td><td>{managementDate(invitation.expiresAt, organization.timezone)}</td><td>{invitation.status === "pending" ? <ApiForm endpoint={`${endpoint}/invitations/${invitation.id}`} method="DELETE" submitLabel="Revocar invitación" /> : "—"}</td></tr>)}</tbody></table></div></div>}</section>
  </>;
}
