import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import pg from "pg";
import { getDatabase } from "../src/lib/db";
import { closeWorkerDatabase } from "../src/lib/worker-db";
import { createCustomer } from "../src/modules/customers/service";
import { createDevice } from "../src/modules/assets/service";
import { acceptInvitation, createInvitation, createOrganization } from "../src/modules/organizations/service";
import { commissionProject, createMeasurementPoint, createProject, createTopologyVersion, replaceBinding } from "../src/modules/projects/persistent";
import { enrollGateway } from "../src/modules/gateways/service";
import { processTelemetryPacket } from "../src/modules/telemetry/processor";
import { closeTelemetryStore } from "../src/modules/telemetry/store";
import { cancelMaintenanceWindow, createAlertRule, createMaintenanceWindow, getAlertHistory, listAlerts, listAlertRules, listNotifications, updateAlertRule } from "../src/modules/alerts/service";
import { addIncidentObservation, createIncident, getIncident, listIncidents, updateIncident } from "../src/modules/incidents/service";
import { createMonitoringWorker, runMonitoringCycle } from "../src/modules/alerts/worker";
import type { TelemetryMessage } from "../src/modules/telemetry/protocol";

const enabled = Boolean(process.env.TEST_RUNTIME_DATABASE_URL && process.env.TEST_ADMIN_DATABASE_URL && process.env.TEST_INGEST_DATABASE_URL && process.env.TEST_WORKER_DATABASE_URL);
test("independent monitor persists alert→assignment→recovery→audited closure, scoped notices, maintenance and outbox retries", { skip: !enabled, timeout: 120000 }, async () => {
  process.env.APP_ENV = "development"; process.env.DATA_ADAPTER = "postgres"; process.env.DEMO_MODE = "false";
  process.env.DATABASE_URL = process.env.TEST_RUNTIME_DATABASE_URL; process.env.INGEST_DATABASE_URL = process.env.TEST_INGEST_DATABASE_URL; process.env.WORKER_DATABASE_URL = process.env.TEST_WORKER_DATABASE_URL;
  const admin = new pg.Pool({ connectionString: process.env.TEST_ADMIN_DATABASE_URL, max: 2, options: "-c timezone=UTC" });
  const tag = randomUUID().slice(0, 8), organizations: string[] = [];
  const owner = { userId: randomUUID(), email: `alert-owner-${tag}@example.test` }, technician = { userId: randomUUID(), email: `alert-tech-${tag}@example.test` }, customerActor = { userId: randomUUID(), email: `alert-customer-${tag}@example.test` }, outsider = { userId: randomUUID(), email: `alert-outsider-${tag}@example.test` };
  const actors = [owner, technician, customerActor, outsider], now = Date.now();
  const ago = (seconds: number) => new Date(now - seconds * 1000).toISOString();
  try {
    for (const actor of actors) await admin.query("INSERT INTO users(id,cognito_subject,email,email_verified,name,updated_at) VALUES($1,$2,$3,true,'Alert fixture',now())", [actor.userId, `test:${actor.userId}`, actor.email]);
    const org = await createOrganization(owner, { name: `Alertas ${tag}`, slug: `alerts-${tag}`, timezone: "America/Bogota" }); organizations.push(org.id);
    const foreignOrg = await createOrganization(outsider, { name: `Ajena ${tag}`, slug: `alerts-other-${tag}`, timezone: "America/Bogota" }); organizations.push(foreignOrg.id);
    const client = await createCustomer(owner, org.id, { name: "Cliente local" });
    const project = await createProject(owner, org.id, { name: "Proyecto monitorizado", customerId: client.id, location: "Yopal", capacityKwp: 6 });
    const hidden = await createProject(owner, org.id, { name: "Proyecto no asignado", customerId: client.id, location: "Yopal", capacityKwp: 6 });
    const foreignClient = await createCustomer(outsider, foreignOrg.id, { name: "Ajeno" });
    const foreignProject = await createProject(outsider, foreignOrg.id, { name: "Ajeno", customerId: foreignClient.id, location: "Yopal", capacityKwp: 6 });
    for (const [actor, role] of [[technician, "technician"], [customerActor, "customer"]] as const) await acceptInvitation(actor, { token: (await createInvitation(owner, org.id, { email: actor.email, role, projectIds: [project.id] })).token });
    const gen = await createMeasurementPoint(owner, org.id, project.id, { name: "Generación", kind: "generation", signConvention: "positive_generation" });
    const grid = await createMeasurementPoint(owner, org.id, project.id, { name: "Red", kind: "grid", signConvention: "positive_import" });
    const genMeter = await createDevice(owner, org.id, { name: "Generación", kind: "meter", serialNumber: `${tag}-GEN` }), gridMeter = await createDevice(owner, org.id, { name: "Red", kind: "meter", serialNumber: `${tag}-GRID` }), gatewayDevice = await createDevice(owner, org.id, { name: "Gateway", kind: "gateway", serialNumber: `${tag}-GW` });
    await replaceBinding(owner, org.id, project.id, { deviceId: genMeter.id, measurementPointId: gen.id, validFrom: ago(7200), configuration: { channel: "1", multiplier: 1 } });
    await replaceBinding(owner, org.id, project.id, { deviceId: gridMeter.id, measurementPointId: grid.id, validFrom: ago(7200), configuration: { channel: "2", multiplier: 1 } });
    await createTopologyVersion(owner, org.id, project.id, { validFrom: ago(7200), configuration: { type: "grid_tied_no_battery", generationPointId: gen.id, gridPointId: grid.id, consumptionPointId: null } });
    await commissionProject(owner, org.id, project.id, { commissionedAt: ago(7100), notes: "Prueba local simulada, sin kit físico." });
    const gateway = await enrollGateway(owner, org.id, { name: "Simulador alertas", source: "simulator", principalId: `alerts-${tag}`, gatewayDeviceId: gatewayDevice.id, meterDeviceIds: [genMeter.id, gridMeter.id] });
    const transport = { source: "simulator" as const, clientId: gateway.id, principalId: gateway.principalId, topic: `solar/v2/gateways/${gateway.id}/telemetry`, receivedAt: new Date() };
    function sample(generation: boolean, seconds: number, quality: TelemetryMessage["quality"] = "measured", alarms?: TelemetryMessage["alarms"]): TelemetryMessage { return { schema_version: "2.0", event_id: randomUUID(), device_id: generation ? genMeter.id : gridMeter.id, measurement_point_id: generation ? gen.id : grid.id, configuration_version: 1, measured_at: ago(seconds), values: { active_power: generation ? 4 : 1, import_energy: null, export_energy: null }, units: { active_power: "kW", import_energy: "kWh", export_energy: "kWh" }, quality, ...(alarms ? { alarms } : {}) }; }
    const ingest = (samples: TelemetryMessage[]) => processTelemetryPacket({ schema_version: "2.0", gateway_id: gateway.id, packet_id: randomUUID(), sent_at: new Date().toISOString(), samples, loss_reports: [] }, { ...transport, receivedAt: new Date() });
    const due = () => admin.query("UPDATE alert_rules SET last_evaluated_at=NULL WHERE organization_id=$1", [org.id]);
    const rule = await createAlertRule(owner, org.id, { projectId: project.id, name: "Calidad explícita", kind: "invalid_data", persistenceSeconds: 0, recoverySeconds: 0, configuration: { maxMeasurementAgeSeconds: 300 } });
    await createAlertRule(owner, org.id, { projectId: hidden.id, name: "Regla reservada", kind: "communication", configuration: {} });
    await assert.rejects(createAlertRule(technician, org.id, { projectId: project.id, name: "No autorizado", kind: "communication", configuration: {} }));
    await assert.rejects(createAlertRule(owner, org.id, { projectId: foreignProject.id, name: "Cruce", kind: "communication", configuration: {} }));
    assert.deepEqual((await listAlertRules(customerActor, org.id)).items.map((entry) => entry.projectId), [project.id]);
    const initial = sample(true, 120, "invalid");
    await ingest([initial, sample(false, 120)]);
    await runMonitoringCycle({ maxProjects: 100, maxNotifications: 0 });
    let alerts = await listAlerts(owner, org.id); assert.equal(alerts.total, 1); assert.equal(alerts.items[0].status, "active");
    const alert = alerts.items[0], incident = (await listIncidents(owner, org.id)).items[0]; assert.equal(incident.alertId, alert.id); assert.equal(incident.status, "open");
    assert.equal((await listAlerts(customerActor, org.id)).total, 1); await assert.rejects(listAlerts(outsider, org.id));
    const reserved = await createIncident(owner, org.id, { projectId: hidden.id, title: "Incidencia reservada", description: "Sin acceso para cliente." });
    await assert.rejects(getIncident(customerActor, org.id, reserved.id));
    await assert.rejects(updateIncident(customerActor, org.id, incident.id, { status: "in_progress" }));
    await assert.rejects(updateIncident(owner, org.id, incident.id, { assigneeUserId: outsider.userId }));
    await updateIncident(owner, org.id, incident.id, { assigneeUserId: technician.userId, status: "in_progress" });
    await addIncidentObservation(owner, org.id, incident.id, { note: "Se revisó el contexto de la lectura simulada." });
    const failing = createMonitoringWorker(undefined, async (notification) => { if (notification.organizationId === org.id) throw new Error("private details"); });
    await failing({ maxProjects: 0, maxNotifications: 100 });
    const failed = (await admin.query("SELECT status,attempts,next_attempt_at,last_error FROM notification_outbox WHERE organization_id=$1", [org.id])).rows[0];
    assert.equal(failed.status, "pending"); assert.equal(failed.attempts, 1); assert.equal(failed.last_error, "IN_APP_PUBLICATION_FAILED"); assert.ok(failed.next_attempt_at.getTime() > Date.now());
    await admin.query("UPDATE notification_outbox SET next_attempt_at=now()-interval '1 second' WHERE organization_id=$1", [org.id]);
    await runMonitoringCycle({ maxProjects: 0, maxNotifications: 100 });
    assert.equal((await listNotifications(customerActor, org.id)).total, 1);
    const published = (await listNotifications(customerActor, org.id)).items[0]; assert.ok(!("leaseTokenHash" in published) && !("workerId" in published));
    await due(); await runMonitoringCycle({ maxProjects: 100, maxNotifications: 0 });
    assert.equal((await admin.query("SELECT count(*)::int AS n FROM notification_outbox WHERE organization_id=$1", [org.id])).rows[0].n, 1);
    await ingest([sample(true, 180)]); await due(); await runMonitoringCycle({ maxProjects: 100, maxNotifications: 0 });
    assert.equal((await listAlerts(owner, org.id)).items[0].status, "active");
    await ingest([sample(true, 60)]); await due(); await runMonitoringCycle({ maxProjects: 100, maxNotifications: 100 });
    assert.equal((await listAlerts(owner, org.id)).items[0].status, "resolved"); assert.equal((await getIncident(owner, org.id, incident.id)).incident.status, "in_progress");
    await updateIncident(owner, org.id, incident.id, { status: "closed", resolution: "Lectura válida recibida y revisión local documentada." });
    const history = await getIncident(owner, org.id, incident.id); assert.equal(history.incident.status, "closed"); assert.ok(history.events.some((event) => event.kind === "closed" && event.actorId === owner.userId));
    assert.equal((await admin.query("SELECT count(*)::int AS n FROM audit_events WHERE organization_id=$1 AND entity_id=$2 AND action='incident.closed'", [org.id, incident.id])).rows[0].n, 1);
    assert.equal((await getAlertHistory(customerActor, org.id, alert.id)).events.length, 2);
    const maintenance = await createMaintenanceWindow(owner, org.id, { projectId: project.id, from: ago(60), to: new Date(now + 3600000).toISOString(), reason: "Prueba de mantenimiento planificado" });
    const comm = await createAlertRule(owner, org.id, { projectId: project.id, name: "Comunicación", kind: "communication", persistenceSeconds: 0, recoverySeconds: 0, configuration: { staleAfterSeconds: 10 } });
    await due(); await runMonitoringCycle({ maxProjects: 100, maxNotifications: 100 }); assert.equal((await listAlerts(owner, org.id, { kind: "communication" })).total, 0);
    await cancelMaintenanceWindow(owner, org.id, maintenance.id, { cancelled: true }); await due(); await runMonitoringCycle({ maxProjects: 100, maxNotifications: 100 });
    assert.equal((await listAlerts(owner, org.id, { kind: "communication", status: "active" })).total, 1);
    await updateAlertRule(owner, org.id, comm.id, { enabled: false }); await due(); await runMonitoringCycle({ maxProjects: 100, maxNotifications: 100 });
    assert.equal((await listAlerts(owner, org.id, { kind: "communication", status: "active" })).total, 0);
    await createAlertRule(owner, org.id, { projectId: project.id, name: "Alarmas reportadas", kind: "device_alarm", persistenceSeconds: 0, recoverySeconds: 0, configuration: {} });
    await ingest([sample(true, 30, "measured", [{ code: "SIMULATED_EXPLICIT", severity: "critical", active: true }])]); await due(); await runMonitoringCycle({ maxProjects: 100, maxNotifications: 100 });
    assert.equal((await listAlerts(owner, org.id, { kind: "device_alarm", status: "active" })).total, 1);
    await ingest([sample(true, 20)]); await due(); await runMonitoringCycle({ maxProjects: 100, maxNotifications: 100 });
    assert.equal((await listAlerts(owner, org.id, { kind: "device_alarm", status: "active" })).total, 1);
    await ingest([sample(true, 10, "measured", [])]); await due(); await runMonitoringCycle({ maxProjects: 100, maxNotifications: 100 });
    assert.equal((await listAlerts(owner, org.id, { kind: "device_alarm", status: "active" })).total, 0);
    await updateAlertRule(owner, org.id, rule.id, { enabled: false });
    const cli = spawnSync(process.execPath, ["--conditions=react-server", "--import", "tsx", "scripts/monitor.ts", "--once"], { env: process.env, encoding: "utf8", timeout: 30000 }); assert.equal(cli.status, 0, cli.stderr); assert.equal(JSON.parse(cli.stdout.trim()).notifications, "in_app");
    alerts = await listAlerts(customerActor, org.id); assert.ok(alerts.items.every((entry) => entry.projectId === project.id));
  } finally {
    await closeWorkerDatabase(); await closeTelemetryStore(); await getDatabase().$disconnect();
    for (const table of ["notification_outbox", "incident_events", "incidents", "alert_events", "alerts", "alert_rules", "maintenance_windows", "telemetry_latest", "telemetry_daily_aggregates", "telemetry_samples", "ingestion_quarantine", "gateway_loss_reports", "gateway_meters", "gateway_identities", "invitation_projects", "invitations", "site_access", "topology_versions", "device_bindings", "measurement_points", "devices", "projects", "customers", "audit_events", "memberships"]) await admin.query(`DELETE FROM ${table} WHERE organization_id=ANY($1::uuid[])`, [organizations]);
    await admin.query("DELETE FROM organizations WHERE id=ANY($1::uuid[])", [organizations]); await admin.query("DELETE FROM users WHERE id=ANY($1::uuid[])", [actors.map((actor) => actor.userId)]); await admin.end();
  }
});
