import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import pg from "pg";
import { getDatabase } from "../src/lib/db";
import { withTenant } from "../src/lib/tenant";
import { createCustomer, listCustomers, updateCustomer } from "../src/modules/customers/service";
import { createDevice, listDevices, retireDevice, updateDevice } from "../src/modules/assets/service";
import { acceptInvitation, createInvitation, createOrganization, listInvitations, listMembers, listOrganizations, revokeInvitation, updateMembership } from "../src/modules/organizations/service";
import { assignParticipant, commissionProject, createMeasurementPoint, createProject, createTopologyVersion, exportProjects, getProjectManagement, listProjects, removeParticipant, replaceBinding, updateProject } from "../src/modules/projects/persistent";

const enabled = Boolean(process.env.TEST_RUNTIME_DATABASE_URL && process.env.TEST_ADMIN_DATABASE_URL);
test("persistent management lifecycle, tenant scope, replacements, invitations and concurrent owner protection", { skip: !enabled, timeout: 120000 }, async () => {
  process.env.APP_ENV = "development";
  process.env.DATA_ADAPTER = "postgres";
  process.env.DEMO_MODE = "false";
  process.env.DATABASE_URL = process.env.TEST_RUNTIME_DATABASE_URL;
  const admin = new pg.Pool({ connectionString: process.env.TEST_ADMIN_DATABASE_URL, max: 2 });
  const tag = randomUUID().slice(0, 8);
  const owner = { userId: randomUUID(), email: `business-owner-${tag}@example.test` };
  const technician = { userId: randomUUID(), email: `business-technician-${tag}@example.test` };
  const customerActor = { userId: randomUUID(), email: `business-customer-${tag}@example.test` };
  const outsider = { userId: randomUUID(), email: `business-outsider-${tag}@example.test` };
  const extraOwner = { userId: randomUUID(), email: `business-extra-owner-${tag}@example.test` };
  const users = [owner, technician, customerActor, outsider, extraOwner];
  const organizationIds: string[] = [];
  try {
    for (const actor of users) await admin.query("INSERT INTO users(id,cognito_subject,email,email_verified,name,updated_at) VALUES($1,$2,$3,true,$4,now())", [actor.userId, `https://cognito-idp.us-east-1.amazonaws.com/test:${actor.userId}`, actor.email, `Fixture ${tag}`]);
    const org = await createOrganization(owner, { name: `Empresa ${tag}`, slug: `business-${tag}`, timezone: "America/Bogota" });
    const foreignOrg = await createOrganization(outsider, { name: `Ajena ${tag}`, slug: `foreign-${tag}`, timezone: "America/Bogota" });
    organizationIds.push(org.id, foreignOrg.id);
    assert.deepEqual((await listOrganizations(owner)).map((entry) => entry.id), [org.id]);
    const client = await createCustomer(owner, org.id, { name: "Cliente Uno" });
    const unassignedClient = await createCustomer(owner, org.id, { name: "Cliente Dos" });
    await updateCustomer(owner, org.id, client.id, { name: "Cliente Uno actualizado" });
    const foreignClient = await createCustomer(outsider, foreignOrg.id, { name: "Cliente ajeno" });
    const project = await createProject(owner, org.id, { customerId: client.id, name: '=HYPERLINK("https://invalid.test")', location: "Yopal", latitude: 5.337, longitude: -72.395, capacityKwp: 6.5 });
    const unassigned = await createProject(owner, org.id, { customerId: unassignedClient.id, name: "Proyecto reservado", location: "Aguazul", capacityKwp: 12 });
    const foreignProject = await createProject(outsider, foreignOrg.id, { customerId: foreignClient.id, name: "Proyecto ajeno", location: "Tauramena", capacityKwp: 4 });
    await updateProject(owner, org.id, project.id, { capacityKwp: 6.8 });
    await assert.rejects(createProject(owner, org.id, { customerId: foreignClient.id, name: "Ataque cliente", location: "Yopal", capacityKwp: 1 }));
    await assert.rejects(getProjectManagement(owner, org.id, foreignProject.id));
    await assert.rejects(listProjects(owner, foreignOrg.id));
    const techInvite = await createInvitation(owner, org.id, { email: technician.email, role: "technician", projectIds: [project.id] });
    const customerInvite = await createInvitation(owner, org.id, { email: customerActor.email, role: "customer", projectIds: [project.id] });
    await acceptInvitation(technician, { token: techInvite.token });
    await acceptInvitation(customerActor, { token: customerInvite.token });
    assert.deepEqual((await listProjects(customerActor, org.id)).items.map((entry) => entry.id), [project.id]);
    assert.deepEqual((await listCustomers(customerActor, org.id)).items.map((entry) => entry.id), [client.id]);
    assert.deepEqual((await listProjects(technician, org.id)).items.map((entry) => entry.id), [project.id]);
    await assert.rejects(getProjectManagement(customerActor, org.id, unassigned.id));
    await assert.rejects(updateProject(technician, org.id, project.id, { name: "Alterado" }), (error: unknown) => error instanceof Error && "status" in error && error.status === 403);
    await assert.rejects(createCustomer(customerActor, org.id, { name: "Inyectado" }));
    await assert.rejects(assignParticipant(owner, org.id, project.id, { userId: outsider.userId, role: "customer" }));
    await removeParticipant(owner, org.id, project.id, technician.userId);
    assert.equal((await listProjects(technician, org.id)).total, 0);
    await assignParticipant(owner, org.id, project.id, { userId: technician.userId, role: "technician" });

    const generation = await createMeasurementPoint(owner, org.id, project.id, { name: "Generación", kind: "generation", signConvention: "positive_generation" });
    const grid = await createMeasurementPoint(owner, org.id, project.id, { name: "Red", kind: "grid", signConvention: "positive_import" });
    const firstMeter = await createDevice(owner, org.id, { name: "Medidor inicial", serialNumber: `${tag}-GEN-1`, kind: "meter" });
    const replacementMeter = await createDevice(owner, org.id, { name: "Medidor reemplazo", serialNumber: `${tag}-GEN-2`, kind: "meter" });
    const gridMeter = await createDevice(owner, org.id, { name: "Medidor red", serialNumber: `${tag}-GRID`, kind: "meter" });
    const gateway = await createDevice(owner, org.id, { name: "Gateway", serialNumber: `${tag}-GW`, kind: "gateway" });
    const foreignMeter = await createDevice(outsider, foreignOrg.id, { name: "Medidor ajeno", serialNumber: `${tag}-FOREIGN`, kind: "meter" });
    await updateDevice(owner, org.id, replacementMeter.id, { name: "Medidor verificado" });
    const instant = Date.now();
    const ago = (minutes: number) => new Date(instant - minutes * 60000).toISOString();
    const initialBinding = await replaceBinding(owner, org.id, project.id, { deviceId: firstMeter.id, measurementPointId: generation.id, validFrom: ago(60), configuration: { channel: "1", multiplier: 1 } });
    await replaceBinding(owner, org.id, project.id, { deviceId: gridMeter.id, measurementPointId: grid.id, validFrom: ago(60), configuration: { channel: "1", multiplier: 1 } });
    await assert.rejects(replaceBinding(owner, org.id, project.id, { deviceId: foreignMeter.id, measurementPointId: generation.id, validFrom: ago(15), configuration: { channel: "1", multiplier: 1 } }));
    await assert.rejects(replaceBinding(owner, org.id, project.id, { deviceId: gateway.id, measurementPointId: generation.id, validFrom: ago(15), configuration: { channel: "1", multiplier: 1 } }));
    const sampleId = randomUUID();
    await admin.query("INSERT INTO telemetry_samples(event_id,organization_id,binding_id,device_id,measurement_point_id,configuration_version,measured_at,received_at,active_power,quality) VALUES($1,$2,$3,$4,$5,1,$6,$6,3.2,'measured')", [sampleId, org.id, initialBinding.id, firstMeter.id, generation.id, ago(30)]);
    await withTenant(owner, org.id, async (tx) => {
      const saved = await tx.telemetrySample.findFirstOrThrow({ where: { organizationId: org.id, bindingId: initialBinding.id } });
      assert.equal(saved.measuredAt.toISOString(), ago(30), "fixture timestamp must survive UTC persistence");
      assert.equal(await tx.telemetrySample.count({ where: { organizationId: org.id, bindingId: initialBinding.id, measuredAt: { gte: new Date(ago(45)) } } }), 1, "runtime owner must see the historical fixture sample in the candidate interval");
    });
    await assert.rejects(replaceBinding(owner, org.id, project.id, { deviceId: replacementMeter.id, measurementPointId: generation.id, validFrom: ago(45), configuration: { channel: "1", multiplier: 1 } }));
    const nextBinding = await replaceBinding(owner, org.id, project.id, { deviceId: replacementMeter.id, measurementPointId: generation.id, validFrom: ago(15), configuration: { channel: "1", multiplier: 1 } });
    assert.equal(nextBinding.configurationVersion, 2);
    await assert.rejects(retireDevice(owner, org.id, replacementMeter.id));
    await retireDevice(owner, org.id, firstMeter.id);
    await createTopologyVersion(owner, org.id, project.id, { validFrom: ago(50), configuration: { type: "grid_tied_no_battery", generationPointId: generation.id, gridPointId: grid.id, consumptionPointId: null } });
    await assert.rejects(createTopologyVersion(owner, org.id, project.id, { validFrom: ago(40), configuration: { type: "grid_tied_no_battery", generationPointId: generation.id, gridPointId: grid.id, consumptionPointId: null } }));
    const nextTopology = await createTopologyVersion(owner, org.id, project.id, { validFrom: ago(5), configuration: { type: "grid_tied_no_battery", generationPointId: generation.id, gridPointId: grid.id, consumptionPointId: null } });
    assert.equal(nextTopology.version, 2);
    await commissionProject(owner, org.id, project.id, { commissionedAt: ago(2), notes: "Polaridad, medidores y topología verificados en prueba local." });
    await assert.rejects(commissionProject(owner, org.id, project.id, { commissionedAt: ago(1), notes: "No se puede duplicar la puesta en marcha." }));
    const detail = await getProjectManagement(owner, org.id, project.id);
    assert.equal(detail.bindings.length, 3);
    assert.equal(detail.bindings.find((binding) => binding.id === initialBinding.id)?.validTo?.toISOString(), nextBinding.validFrom.toISOString());
    assert.equal(detail.topologyVersions.length, 2);
    assert.ok(detail.history.some((event) => event.action === "binding.replaced"));
    assert.ok(detail.history.some((event) => event.action === "project.commissioned"));
    assert.equal((await listDevices(customerActor, org.id)).items.some((device) => device.id === foreignMeter.id), false);
    const csv = await exportProjects(customerActor, org.id);
    assert.ok(csv.includes(project.id));
    assert.ok(csv.includes("'=HYPERLINK"));
    assert.equal(csv.includes(unassigned.id), false);
    assert.equal(csv.includes(foreignProject.id), false);
    assert.equal((await admin.query("SELECT binding_id,configuration_version FROM telemetry_samples WHERE event_id=$1", [sampleId])).rows[0].binding_id, initialBinding.id);

    const tokenless = await listInvitations(owner, org.id);
    assert.ok(tokenless.every((entry) => !("token" in entry) && !("tokenHash" in entry)));
    const expired = await createInvitation(owner, org.id, { email: extraOwner.email, role: "owner", projectIds: [] });
    await admin.query("UPDATE invitations SET created_at=now()-interval '1 day', expires_at=now()-interval '1 second' WHERE id=$1", [expired.id]);
    await assert.rejects(acceptInvitation(extraOwner, { token: expired.token }));
    const revoked = await createInvitation(owner, org.id, { email: extraOwner.email, role: "owner", projectIds: [] });
    await revokeInvitation(owner, org.id, revoked.id);
    await assert.rejects(acceptInvitation(extraOwner, { token: revoked.token }));
    const ownerInvite = await createInvitation(owner, org.id, { email: extraOwner.email, role: "owner", projectIds: [] });
    await assert.rejects(acceptInvitation(outsider, { token: ownerInvite.token }));
    const acceptance = await Promise.allSettled([acceptInvitation(extraOwner, { token: ownerInvite.token }), acceptInvitation(extraOwner, { token: ownerInvite.token })]);
    assert.equal(acceptance.filter((entry) => entry.status === "fulfilled").length, 1);
    assert.equal(acceptance.filter((entry) => entry.status === "rejected").length, 1);
    assert.equal((await listMembers(owner, org.id)).filter((entry) => entry.userId === extraOwner.userId).length, 1);

    // A separate connection and a disconnected Prisma client both see persisted state.
    await getDatabase().$disconnect();
    const persisted = await getProjectManagement(owner, org.id, project.id);
    assert.equal(persisted.bindings.length, 3);
    assert.ok(persisted.commissionedAt);
    assert.equal((await admin.query("SELECT count(*)::int AS n FROM telemetry_samples WHERE event_id=$1", [sampleId])).rows[0].n, 1);

    const activeOwners = (await listMembers(owner, org.id)).filter((entry) => entry.role === "owner" && entry.status === "active");
    const ownership = await Promise.allSettled(activeOwners.map((membership) => updateMembership(membership.userId === owner.userId ? owner : extraOwner, org.id, membership.id, { status: "disabled" })));
    assert.equal(ownership.filter((entry) => entry.status === "fulfilled").length, 1);
    const survivor = ownership[0].status === "rejected" ? activeOwners[0].userId : activeOwners[1].userId;
    await withTenant({ userId: survivor }, org.id, async (tx) => { assert.equal(await tx.membership.count({ where: { organizationId: org.id, role: "owner", status: "active" } }), 1); });
  } finally {
    await getDatabase().$disconnect();
    // Remove only this run's random UUID fixtures from the dedicated local test DB.
    for (const table of ["telemetry_samples", "invitation_projects", "site_access", "topology_versions", "device_bindings", "measurement_points", "devices", "projects", "customers", "invitations", "audit_events", "memberships"]) await admin.query(`DELETE FROM ${table} WHERE organization_id = ANY($1::uuid[])`, [organizationIds]);
    await admin.query("DELETE FROM organizations WHERE id = ANY($1::uuid[])", [organizationIds]);
    await admin.query("DELETE FROM users WHERE id = ANY($1::uuid[])", [users.map((entry) => entry.userId)]);
    await admin.end();
  }
});
