import Link from "next/link";
import { listAlertRules, listAlerts, listMaintenanceWindows, listNotifications } from "@/modules/alerts/service";
import { listIncidents } from "@/modules/incidents/service";
import type { Actor } from "@/modules/organizations/access";
import { formatDate } from "@/lib/format";
import { ApiForm, type ManagementField } from "./management-form";
import { EmptyState, PageHeader, StatusBadge } from "./ui";

export const alertKindLabels = { communication: "Comunicación", invalid_data: "Datos inválidos", generation: "Generación esperada", device_alarm: "Alarma del equipo" };
const date = (value: Date | null, zone?: string) => formatDate(value?.toISOString(), zone);
type Project = { id: string; name: string; timezone?: string };
export async function OperationalAlerts({ identity, organizationId, projects, canManage, status, page = 1 }: { identity: Actor; organizationId: string; projects: Project[]; canManage: boolean; status?: string; page?: number }) {
  const filter = ["pending", "active", "resolved"].includes(status ?? "") ? status as "pending" | "active" | "resolved" : undefined;
  const [alerts, incidents, rules, maintenance, notifications] = await Promise.all([
    listAlerts(identity, organizationId, { status: filter, page, pageSize: 20 }), listIncidents(identity, organizationId, { pageSize: 50 }), listAlertRules(identity, organizationId, { pageSize: 50 }), listMaintenanceWindows(identity, organizationId, { pageSize: 50 }), listNotifications(identity, organizationId, { pageSize: 20 }),
  ]);
  const base = `/api/v1/organizations/${organizationId}`, org = `org=${organizationId}`;
  const zone = (projectId: string) => projects.find((project) => project.id === projectId)?.timezone;
  const projectField: ManagementField = { name: "projectId", label: "Proyecto", type: "select", required: true, options: projects.map((project) => ({ value: project.id, label: project.name })) };
  const common: ManagementField[] = [projectField, { name: "name", label: "Nombre de la regla", required: true }, { name: "persistenceSeconds", label: "Persistencia (segundos)", type: "number", min: 0, max: 86400, step: "1", required: true, defaultValue: "300", hint: "Tiempo continuo antes de emitir la alerta." }, { name: "recoverySeconds", label: "Recuperación (segundos)", type: "number", min: 0, max: 86400, step: "1", required: true, defaultValue: "120" }];
  const policies: { kind: keyof typeof alertKindLabels; fixed?: Record<string, unknown>; fields: ManagementField[] }[] = [
    { kind: "communication", fields: [{ name: "configuration.staleAfterSeconds", label: "Antigüedad máxima de lectura/recepción (segundos)", type: "number", min: 10, max: 86400, required: true, defaultValue: "900", step: "1" }] },
    { kind: "invalid_data", fields: [{ name: "configuration.maxMeasurementAgeSeconds", label: "Vigencia de medición (segundos)", type: "number", min: 10, max: 86400, required: true, defaultValue: "300", step: "1" }] },
    { kind: "generation", fixed: { configuration: { weekdays: [0, 1, 2, 3, 4, 5, 6] } }, fields: [{ name: "configuration.startLocalTime", label: "Inicio de generación esperada (HH:mm)", required: true, hint: "Hora local del proyecto; regla diaria." }, { name: "configuration.endLocalTime", label: "Fin de generación esperada (HH:mm)", required: true }, { name: "configuration.minimumPowerKw", label: "Potencia mínima esperada (kW)", type: "number", min: 0, required: true }, { name: "configuration.maxMeasurementAgeSeconds", label: "Vigencia de medición (segundos)", type: "number", min: 10, max: 86400, required: true, defaultValue: "300", step: "1" }] },
    { kind: "device_alarm", fixed: { configuration: { minimumSeverity: "warning" } }, fields: [{ name: "configuration.maxMeasurementAgeSeconds", label: "Vigencia de medición (segundos)", type: "number", min: 10, max: 86400, required: true, defaultValue: "300", step: "1" }] },
  ];
  return <>
    <PageHeader title="Alertas y seguimiento" description="Distingue problemas de comunicación, calidad de datos, generación esperada y alarmas reportadas por el equipo." />
    <section className="panel" aria-labelledby="operational-alerts-title"><div className="panel-header"><div><h2 id="operational-alerts-title">Registro de alertas</h2><p>{alerts.total} resultados · Fechas en la zona horaria de cada proyecto</p></div></div>
      <form className="toolbar" action="/alerts"><input name="org" type="hidden" value={organizationId} /><label className="field"><span>Estado</span><select name="status" defaultValue={filter ?? "all"}><option value="all">Emitidas</option><option value="active">Activas</option><option value="resolved">Resueltas</option><option value="pending">En observación</option></select></label><button className="button" type="submit">Aplicar filtros</button><Link className="button button-secondary" href={`/alerts?${org}`}>Limpiar</Link></form>
      {alerts.items.length ? <><p className="table-scroll-hint">Desliza la tabla para ver el estado y la última evaluación.</p><div className="table-wrap" role="region" aria-label="Tabla de alertas con desplazamiento horizontal" tabIndex={0}><table className="data-table"><caption className="visually-hidden">Alertas autorizadas de la organización</caption><thead><tr><th scope="col">Alerta</th><th scope="col">Proyecto</th><th scope="col">Estado</th><th scope="col">Última evaluación</th></tr></thead><tbody>{alerts.items.map((alert) => <tr key={alert.id}><th scope="row"><Link className="inline-link" href={`/alerts/${alert.id}?${org}`}>{alert.title}</Link><span className="table-subtitle muted">{alertKindLabels[alert.rule.kind]} · {alert.message}</span></th><td><Link className="inline-link" href={`/projects/${alert.projectId}?${org}`}>{alert.project.name}</Link></td><td><StatusBadge status={alert.status} /><span className="table-subtitle"><StatusBadge status={alert.severity} /></span></td><td>{date(alert.lastEvaluatedAt, zone(alert.projectId))}</td></tr>)}</tbody></table></div></> : <EmptyState title="Sin alertas para esta consulta" description="Las reglas requieren datos y evaluación periódica. La ausencia de una alerta no confirma el funcionamiento eléctrico del sitio." />}
      {alerts.total > 20 && <div className="form-actions">{page > 1 && <Link className="button button-secondary" href={`/alerts?${org}&status=${filter ?? "all"}&page=${page - 1}`}>Anterior</Link>}<span>Página {page} de {Math.ceil(alerts.total / 20)}</span>{page * 20 < alerts.total && <Link className="button button-secondary" href={`/alerts?${org}&status=${filter ?? "all"}&page=${page + 1}`}>Siguiente</Link>}</div>}
    </section>
    <section className="panel" aria-labelledby="incidents-title"><div className="panel-header"><div><h2 id="incidents-title">Incidencias</h2><p>La recuperación de una alerta conserva la incidencia hasta su cierre con una resolución.</p></div></div>{incidents.items.length ? <><p className="table-scroll-hint">Desliza la tabla para ver el estado y el responsable.</p><div className="table-wrap" role="region" aria-label="Tabla de incidencias con desplazamiento horizontal" tabIndex={0}><table className="data-table"><caption className="visually-hidden">Últimas 50 incidencias autorizadas</caption><thead><tr><th scope="col">Incidencia</th><th scope="col">Proyecto</th><th scope="col">Estado</th><th scope="col">Responsable</th></tr></thead><tbody>{incidents.items.map((incident) => <tr key={incident.id}><th scope="row"><Link className="inline-link" href={`/incidents/${incident.id}?${org}`}>{incident.title}</Link></th><td>{incident.project.name}</td><td><StatusBadge status={incident.status} /></td><td>{incident.assigneeUserId ? "Asignado" : "Por asignar"}</td></tr>)}</tbody></table></div></> : <EmptyState title="Sin incidencias registradas" description="Las alertas emitidas abren una incidencia. También puedes registrar una revisión manual." />}
      {canManage && projects.length > 0 && <details className="management-details"><summary>Registrar incidencia</summary><ApiForm endpoint={`${base}/incidents`} submitLabel="Registrar incidencia" redirectTo={`/incidents/{id}?${org}`} fields={[projectField, { name: "title", label: "Título", required: true }, { name: "description", label: "Descripción", type: "textarea" }]} /></details>}
    </section>
    <section className="panel" aria-labelledby="rules-title"><div className="panel-header"><div><h2 id="rules-title">Reglas de detección</h2><p>{rules.total} reglas · Una falta de comunicación no se interpreta como falla eléctrica.</p></div></div>{rules.items.length ? <ul className="alert-list">{rules.items.map((rule) => <li className="alert-card" key={rule.id}><h3>{rule.name}</h3><p>{rule.project.name} · {alertKindLabels[rule.kind]} · {rule.enabled ? "Habilitada" : "Pausada"}</p><p className="muted">Persistencia: {rule.persistenceSeconds} s · Recuperación: {rule.recoverySeconds} s</p>{canManage && <ApiForm endpoint={`${base}/alert-rules/${rule.id}`} method="PATCH" fixed={{ enabled: !rule.enabled }} submitLabel={rule.enabled ? "Pausar regla" : "Habilitar regla"} />}</li>)}</ul> : <EmptyState title="Todavía no hay reglas" description="Configura los tiempos y las condiciones según cada instalación para iniciar la detección." />}
      {canManage && projects.length > 0 && <details className="management-details"><summary>Configurar una regla</summary><p className="muted">La generación esperada requiere un horario y un umbral definidos para el proyecto. Las alarmas del equipo requieren que el dispositivo las reporte.</p>{policies.map((policy) => <details className="management-details" key={policy.kind}><summary>{alertKindLabels[policy.kind]}</summary><ApiForm endpoint={`${base}/alert-rules`} submitLabel="Crear regla" fixed={{ ...policy.fixed, kind: policy.kind }} fields={[...common, ...policy.fields]} /></details>)}</details>}
    </section>
    <section className="panel" aria-labelledby="maintenance-title"><div className="panel-header"><div><h2 id="maintenance-title">Mantenimientos</h2><p>Durante la ventana se suspenden nuevas activaciones y se reinician los tiempos de observación; las alertas e incidencias abiertas se conservan.</p></div></div>{maintenance.items.length ? <ul className="alert-list">{maintenance.items.map((window) => <li className="alert-card" key={window.id}><h3>{window.project.name}</h3><p>{window.reason}</p><p className="muted">{date(window.from, zone(window.projectId))} a {date(window.to, zone(window.projectId))} · {window.cancelledAt ? "Cancelado" : window.to < new Date() ? "Finalizado" : window.from <= new Date() ? "En curso" : "Programado"}</p>{canManage && !window.cancelledAt && window.to > new Date() && <ApiForm endpoint={`${base}/maintenance-windows/${window.id}`} method="PATCH" fixed={{ cancelled: true }} submitLabel="Cancelar mantenimiento" />}</li>)}</ul> : <p className="empty-inline">No hay ventanas de mantenimiento registradas.</p>}{canManage && projects.length > 0 && <details className="management-details"><summary>Programar mantenimiento</summary><ApiForm endpoint={`${base}/maintenance-windows`} submitLabel="Programar mantenimiento" fields={[projectField, { name: "from", label: "Inicio", type: "datetime-local", required: true, hint: "Se utiliza la zona horaria de tu navegador." }, { name: "to", label: "Fin", type: "datetime-local", required: true }, { name: "reason", label: "Motivo", type: "textarea", required: true }]} /></details>}</section>
    <section className="panel" aria-labelledby="notifications-title"><div className="panel-header"><div><h2 id="notifications-title">Avisos del portal</h2><p>Últimos 20 avisos entregados · Los avisos permanecen disponibles en el portal.</p></div></div>{notifications.items.length ? <ul className="alert-list">{notifications.items.map((notice) => <li className="alert-card" key={notice.id}><Link className="inline-link" href={`/alerts/${notice.alertId}?${org}`}>{notice.project.name} · {notice.eventKind === "activated" ? "Alerta emitida" : "Recuperación registrada"}</Link><p className="muted">{date(notice.deliveredAt, zone(notice.projectId))}</p></li>)}</ul> : <p className="empty-inline">Todavía no hay avisos entregados.</p>}</section>
  </>;
}

export async function AttentionQueue({ identity, organizationId }: { identity: Actor; organizationId: string }) {
  const [alerts, incidents] = await Promise.all([listAlerts(identity, organizationId, { status: "active", pageSize: 5 }), listIncidents(identity, organizationId, { status: "open", pageSize: 5 })]);
  return <section className="panel attention-panel" aria-labelledby="attention-title"><div className="panel-header"><div><h2 id="attention-title">Requieren atención</h2><p>{alerts.total} alertas activas · {incidents.total} incidencias abiertas</p></div><Link className="inline-link" href={`/alerts?org=${organizationId}`}>Gestionar seguimiento</Link></div>{alerts.items.length ? alerts.items.map((alert) => <div className="attention-row" key={alert.id}><div><h3>{alert.project.name}</h3><p>{alert.title}</p></div><Link className="inline-link" href={`/alerts/${alert.id}?org=${organizationId}`}>Revisar alerta</Link></div>) : <p className="empty-inline">Sin alertas activas. Consulta las incidencias que aún requieren seguimiento.</p>}</section>;
}



